#Configuration details for the application

#Connection details for the Avaya CMS/ECHI host
echi_host:      localhost
echi_port:      22
echi_username:  anonymous
echi_password:  
echi_connect_type:  ftp #only ftp supported now, possible for ssh in the future
echi_ftp_directory:  #/Users/ftp/anonymous #If blank/nil, the system will not do a CD at the start
echi_ftp_retry: 10
echi_ftp_delete:  Y #to not delete the files off of the FTP server set to N, Y to delete the files
echi_schema: extended_version13.yml
echi_format: BINARY #valid settings are ASCII or BINARY
echi_process_log: Y #valid is Y/N to turn it on or off
echi_update_agent_data:  N #Insert data in the 'echi_agents' table with the 'agname.dat' file, and update regularly (not available when 'pco_process' set to 'Y')
echi_update_agent_data_freq:  24 #Number of hours to wait before updating the 'echi_agents' table

#Currently only ftp supported, but may want to add SSH/SFTP later
echi_xfer_type: ftp

#How frequently to fetch records off of the Avaya CMS ftp server
fetch_interval: 60  #in seconds

#Whether or not to insert into a database, into a csv file or both
export_type:    database

#Options are:
    #FATAL:	an unhandleable error that results in a program crash
    #ERROR:	a handleable error condition
    #WARN:	a warning
    #INFO:	generic (useful) information about system operation
    #DEBUG:	low-level information for developers
    #NONE:  turn off logging
log_level:  DEBUG
#How many log files to create and the length before cycling through
log_number: 10
#The size of each individual log file
log_length: 10240000

#Email address to send alerts to, specifically failures to connect to the DB or FTP servers
#currently does not support an SMTP server that requires authentication
alert_email_address: youremail@yourdomain.com
smtp_server: smtp.yourdomain.com
smtp_port: 25

#Special settings for a specific application database
pco_process: N #Set to yes (Y) or no (N) if running with a PCO database