#Configuration details for the application

#Connection details for the Avaya CMS/ECHI host
echi_host:      localhost
echi_port:      22
echi_username:  jsgoecke
echi_password:  sanfran2007!
echi_connect_type:  ftp #only ftp supported now, possible for ssh in the future
echi_ftp_directory:  /Users/ftp/anonymous
echi_ftp_retry: 3
echi_ftp_delete:  N #to not delete the files off of the FTP server set to N
echi_schema: extended_version13.yml
echi_format: ASCII #valid settings are ASCII or BINARY
echi_process_log: Y #valid is Y/N to turn it on or off

#Currently only ftp supported, but may want to add UUCP/Serial later
echi_xfer_type: ftp

#How frequently to fetch records off of the Avaya CMS ftp server
fetch_interval: 60  #in seconds

#Whether or not to insert into a database, into a csv file or both
export_type:    database

#Options are:
    #FATAL:	an unhandleable error that results in a program crash
    #ERROR:	a handleable error condition
    #WARN:	a warning
    #INFO:	generic (useful) information about system operation
    #DEBUG:	low-level information for developers
    #NONE:  turn off logging
log_level:  DEBUG
#How many log files to create and the length before cycling through
log_number: 10
#The size of each individual log file
log_length: 10240000

#Special settings for a specific application database
pco_process: N #Set to yes or no if running with a PCO database
pco_record_tablename: PCO_ECHIRECORD
pco_record_seqname: PCO_ECHIRECORDSEQ
pco_log_tablename: PCO_ECHILOG
pco_log_seqname: PCO_ECHILOGSEQ